### ISSUE TITLE
Status bar icon is tiny and out of place

### ISSUE THREAD

**Issue by YamiYukiSenpai** [snapcrafters/cumulonimbus#9]
![image](https://user-images.githubusercontent.com/13153124/56785173-e9c71c00-67c1-11e9-9f75-e01990c648bc.png)

**Comment by kz6fittycent** [comment]
Hi is this still an issue? I can't duplicate it here.

![image](https://github.com/snapcrafters/cumulonimbus/assets/14829816/f38e3c53-ca01-469a-97d7-27aa6a079054)

**Comment by kz6fittycent** [comment]
Closing ticket, as cannot duplicate. @YamiYukiSenpai if you notice the issue return, or it's continuing to present, feel free to open a new issue.
